### PR TITLE
handle youtube.com/v/<id> urls

### PR DESCRIPTION
**Pull request by andrewroth**
handle youtube.com/v/<id> urls

### CODE REVIEW

**Comment by claudiofullscreen** [comment]
Wow, I didn't know that was a thing.

And actually… I'm going to have to update to youtube.com/c/... for channels too :sob:

**Comment by claudiofullscreen** [comment]
Thanks!! :+1: :tada: :grin:

**Comment by stavro** [comment]
FYI `youtube.com/c/` urls are Google+ names, not YouTube usernames, they can change (eg http://youtube.com/c/sÉanswild), and they were not exposed via a lookup API last time I checked.. so I don't believe `Yt` can support them right now :cry:

**Comment by andrewroth** [comment]
No prob.. I was looking for a list of all the different ways of accessing a yt video, but I couldn't find anything.. It seems /v/ is some sort of full-screen view.. we have some users on our site entering youtube urls like that

**Pull request merged**
