### PR TITLE
Only require core_ext/hash from ActiveSupport

### PR DESCRIPTION
**Pull request by jrostand**
This changes only two other files where `String#in?` was used. They now use `Array#include?`.

### CODE REVIEW

**Comment by aharpole** [comment]
How I've missed your pull requests!

**Comment by claudiofullscreen** [comment]
From ActiveSupport documentation:

1.1 Stand-Alone Active Support
In order to have a near-zero default footprint, Active Support does not load anything by default. It is broken in small pieces so that you can load just what you need, and also has some convenience entry points to load related extensions in one shot, even everything.

Thus, after a simple require like:

```
require 'active_support'
```

objects do not even respond to `blank?`.

**Comment by claudiofullscreen** [comment]
My comment above is to say that the following line should not be removed:

```
require 'active_support'
```

On the other hand, what's the reason behind wanting to remove `require 'active_support/core_ext'` ?

**Comment by jrostand** [comment]
@claudiofullscreen the issue I ran into was that including the whole `core_ext` module was making trouble in my app, which doesn't itself use ActiveSupport. It seemed logical to me to remove the more general `require` in the same stroke. Limited core extensions means less chance to interact negatively with an existing codebase.

**Comment by claudiofullscreen** [comment]
Exactly what kind of trouble?

**Comment by jrostand** [comment]
Among other things I was having tests fail for expecting certain objects' `#to_s` to return one value, but having AS change that. Sorry, but I can't give much more detail than that.

**Comment by claudiofullscreen** [comment]
I'm sorry, but I need more details to consider this kind of pull request.

I don't want to preclude the chance to use other methods provided by ActiveSupport's core extensions without a valid and reproducible reason.

Feel free to re-open if you can provide more details.

**Pull request closed without merging**
