### PR TITLE
Registration of Procs to handle access_token updates

### PR DESCRIPTION
**Pull request by stavro**
Registration of handlers to be notified of authentication updates.

``` ruby
Yt.configure do |config|
  config.authentication_handlers << Proc.new {|account|  } #save account.access_token to your db
end
```

or via a ruby class that responds to `call`:

``` ruby
class AuthHandler
  def call(account)
    #save account.access_token to your database
  end
end

Yt.configure do |config|
  config.authentication_handlers << AuthHandler.new #save account.access_token to your db
end
```

### CODE REVIEW

**Comment by claudiofullscreen** [comment]
@stavro Is this still a thing?

**Comment by stavro** [comment]
Yt still does not have a proper solution for this.  We use this code inside
of ProjectCloud for keeping the access token up to date.

**Comment by stavro** [comment]
:beers: One year anniversary of this pull request! :beers:

**Comment by ToadJamb** [comment]
Why has this not been pulled in?

**Comment by claudiofullscreen** [comment]
@ToadJamb what are you doing here? :open_mouth:

**Comment by ToadJamb** [comment]
Because I believe in open source.

...and because I was attempting to use this gem and it seems silly that I cannot easily cache the access token.

**Comment by claudiofullscreen** [comment]
What can I say? I haven't had time to test this. Feel free to open a PR with tests attached :ribbon:

**Comment by claudiofullscreen** [comment]
I will gladly accept a PR with passing tests. :grimacing:

**Comment by sean-atv** [comment]
Closing in favor of https://github.com/Fullscreen/yt/pull/233!  :dancers: with tests

**Comment by stavro** [comment]
Closing in favor of #233!  :dancers: with tests

**Pull request closed without merging**
