### PR TITLE
Youtube has more than one types of rate limits, so 'Exceeded' should cover more.

### PR DESCRIPTION
**Pull request by philipqnguyen**
Previously, "quotaExceeded" was too specific, so "Exceeded" should cover more of youtube's rate limit errors.

### CODE REVIEW

**Comment by claudiofullscreen** [comment]
Great!

I would be even more generic and make that reggae _case insensitive_.

Then add CHANGELOG, bump version :)

**Comment by claudiofullscreen** [comment]
Thanks OS X for auto-correcting regex into reggae

**Comment by philipqnguyen** [comment]
Pushed up some more commits. Should be case insensitive now. Version bumped to 0.25.29 and added to the changelog.

**Comment by claudiofullscreen** [comment]
Great job! :clap: :dancer: :tada:

**Pull request merged**
