### PR TITLE
added missing endpoints for youtube analytics and fixes for start date and end date filters

### PR DESCRIPTION
**Pull request by Shatabdi**

### CODE REVIEW

**Comment by Shatabdi** [comment]
The start date and end date was submitted in wrong format when  the YouTube Api was called.I have fixed the issue and generated the dates in accordance to the format provided in YouTube documentation.

Also there are some missing endpoints in the Gem(annotation_impressions, annotation_clickable_impressions and annotation_closable_impressions). I have added them so that we can directly use the gem to pull the endpoints.

**Comment by claudiofullscreen** [comment]
> The start date and end date was submitted in wrong format when the YouTube Api was called.

Hello @Shatabdi ! What do you mean by "was submitted in wrong format"?

**Comment by paulccarey** [comment]
I believe I am also experiencing the date issue reported here when attempting analytic style requests.
```ruby
account.channel.viewer_percentage
Yt::Errors::RequestError: A request to YouTube API failed:
{"error"=>{"errors"=>[{"domain"=>"global", "reason"=>"invalidParameter", "message"=>"Invalid value '08/12/2016'. Values must match the following regular expression: '[0-9]{4}-[0-9]{2}-[0-9]{2}'", "locationType"=>"parameter", "location"=>"end-date"}, {"domain"=>"global", "reason"=>"invalidParameter", "message"=>"Invalid value '01/02/2005'. Values must match the following regular expression: '[0-9]{4}-[0-9]{2}-[0-9]{2}'", "locationType"=>"parameter", "location"=>"start-date"}], "code"=>400, "message"=>"Invalid value '08/12/2016'. Values must match the following regular expression: '[0-9]{4}-[0-9]{2}-[0-9]{2}'"}}
```

I have not as yet tried the fixes included here but will do so shortly.

**Comment by paulccarey** [comment]
can confirm that the fixes for the date issue appear to work. 👍

**Comment by dgb** [comment]
Hi there,

My name is Derek and I'm now one of the maintainers of the Yt gem. I want to both thank you for your contribution and apologize for the lack of feedback on your pull request. Maintaining an open source project like Yt is a pretty big job, and we're taking steps to prioritize maintenance and development of the project. We're hoping to review community contributions on a regular basis, as well as provide a roadmap for our development plans.

As part of this process we're going through the open PRs and taking action on each one, and for this PR we've chosen to close it. Unfortunately due to the sheer number of PRs and amount of time that's passed, we can't address your PR individually. If you'd like our thoughts, feel free to comment on your PR, and we'll try and get back to you in a timely manner. In lieu of that, some of the reasons we've closed PRs are:

* a lack of tests. We strive for comprehensive coverage; this is important to us
* the passage of time: things that were relevant when the PR was opened might not be as important anymore
* feature need. Since adding features requires us to maintain them, we want to add features that many people will use

Thanks again for your contribution, and please let us know if you have any questions or comments.

**Pull request closed without merging**
