### PR TITLE
Add recording details to video

### PR DESCRIPTION
**Pull request by dxg**
As per [the spec](https://developers.google.com/youtube/v3/docs/videos#recordingDetails).
Please let me know if this needs anything more for merging.

### CODE REVIEW

**Comment by shaicoleman** [comment]
Any reason why this can't be merged?

**Comment by dxg** [comment]
Since writing this, I've switched to using https://rubygems.org/gems/google-api-client/ .
It was a bit tricky to get it set up & running, but the API of that package is far more flexible than this one. I highly recommend using it instead.

**Comment by dgb** [comment]
Hi there,

My name is Derek and I'm now one of the maintainers of the Yt gem. I want to both thank you for your contribution and apologize for the lack of feedback on your pull request. Maintaining an open source project like Yt is a pretty big job, and we're taking steps to prioritize maintenance and development of the project. We're hoping to review community contributions on a regular basis, as well as provide a roadmap for our development plans.

As part of this process we're going through the open PRs and taking action on each one, and for this PR we've chosen to review it. You can expect some more specific feedback in the next week or so.

Thanks again for your contribution, and please let us know if you have any questions or comments.

**Comment by dgb** [comment]
I took a closer look at this and it sounds like these attributes are deprecated, so I'm going to close this PR. Thanks for your contribution @dxg, and sorry we didn't get back to you sooner!

**Pull request closed without merging**
