### PR TITLE
Add comments section to github pages

### PR DESCRIPTION
**Pull request by MoTai**
Added comments introduction to the github pages.

### CODE REVIEW

**Comment by claudiofullscreen** [comment]
Wow!! I'll take a look soon. Thanks!!

On Wednesday, April 6, 2016, Qiang Han notifications@github.com wrote:

> ## Added comments introduction to the github pages.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/Fullscreen/yt/pull/273
> Commit Summary
> - Add comments section to github pages
> 
> File Changes
> - _M_ _layouts/default.html
>   https://github.com/Fullscreen/yt/pull/273/files#diff-0 (7)
> - _A_ comments.html
>   https://github.com/Fullscreen/yt/pull/273/files#diff-1 (46)
> 
> Patch Links:
> - https://github.com/Fullscreen/yt/pull/273.patch
> - https://github.com/Fullscreen/yt/pull/273.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Fullscreen/yt/pull/273

## 

 Claudio Baccigalupo  | Manager, Software Engineering  |  Fullscreen, Inc.
http://www.fullscreen.com

**Comment by claudiofullscreen** [comment]
This is really good!! Here are my comments.

I consider anything that is `Yt::Collections:...` part of the **private API**. 
It's not something that I intend to make public (I think it's too complex), so it's not something I'm keen on documenting.

So for now I would just skip some sections that you wrote. You did the right thing, but I'd rather not give the impressions that users have to invoke `Collections` directly:

screen shot 2016-04-06 at 6 14 14 pm

**Comment by MoTai** [comment]
@claudiofullscreen should be fine now.

**Comment by claudiofullscreen** [comment]
You are the best!

**Pull request merged**
